sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - master

# test versions for go provided by gimme
go:
  - 1.4
  - 1.5
  - 1.5.1
  - tip

install:
  - go get -t -v ./...

script:
  - go test -v -race ./...

matrix:
  allow_failures:
    - go: master
  fast_finish: true
